check-links, cvs-sync, micro-www-checkout, transvalid-batch, transvalid-po, www-commit - update/fix explanations, version & copyright; - cosmetic changes.
check-links
- close the terminal manually.

cvs-sync
- unfuzzify the strings for which no change is detected by add-fuzzy-diff;
- define a PO editor (which can be a text editor) to display outdated POs;
  in previous versions, the same editor was used by cvs-sync and check-links,
  so it couldn't be a PO editor;
- optionally use a local version of gnun-add-fuzzy-diff and add-fuzzy-diff;
- close the terminal manually.

micro-www-checkout
- simplify language-code input;
- user > savannah_user (possible confusion with the $USER environment
  variable);
- add an option to create the team directory;
- add an option to copy missing POs to www-LANG.

transvalid-batch:
- close the terminal manually.

transvalid-po:
- test for  the GNUN-SLOT marker in msgstr;
- use the local version of xhtml1-strict.dtd;
- delete all obsolete strings, including those with external links;
- use the compendium (fr.po) to update files in proprietary/.
- close the terminal manually.

www-commit:
- add the possibility to simply copy the POs from www-fr to www (useful for new
  translations);
- clearer choice of what to do with each batch.

diff --git a/cvs-sync b/cvs-sync
--- a/cvs-sync
+++ b/cvs-sync
@@ -22,22 +22,23 @@
 #       untranslated strings, as well as the POs that have been modified or
 #       lack a counterpart in www (possibly indicating that they are new
 #       translations).
-#    4. Up-to-date POs that differ but have the same PO-Revision-Date in www
-#       and www-team are assumed to be formatted differently. The www version
-#       is copied to www-team. Likewise POs that are up-to-date in www but not
+#    4. POs that are up-to-date in www but not in www-team are copied from www
+#       to www-team.
+#    5. Up-to-date POs that differ but have the same PO-Revision-Date in www
+#       and www-team are copied from www to www-team, but the version in
+#       www-team is saved. 
+#    6. If any POs are present in www but not in www-team, they are installed
 #       in www-team.
-#    5. If any POs are present in www but not in www-team, they are installed
-#       in www-team.
-#    6. If a GUI or PO editor has been specified, the outdated PO files are
-#       displayed unless the -n switch is used.
-#    7. [Git repo only] After the report, and optionally the POs, have been
+#    7. If a PO editor has been specified, the outdated PO files are displayed
+#       unless the -n switch is used.
+#    8. [Git repo only] After the report, and optionally the POs, have been
 #       displayed, the user is prompted to send the list of outdated POs to a
 #       specified address and commit them to the Git repo. This requires
 #       setting the email address and subject line. The message is sent with
-#       Mutt. [This could be extended to CVS repos, but the commits would be
-#       irreversible.]
-#    8. [Git repo only] The up-to-date POs that were copied to www-team are
-#       committed to Git.
+#       Mutt.
+#    9. [Git repo only] The up-to-date POs that were copied to www-team are
+#       committed to Git. This could be extended to CVS repos, but the commits
+#       would be irreversible.
 #
 #    Requirements:
 #    * www and www-team must have the same parent directory.
@@ -67,8 +68,8 @@ set -o pipefail
 
 function version () {
 cat <<EOF
-${0##*\/} version 0.1
-Copyright (C) 2013, 2014 Thérèse Godefroy
+${0##*\/} version 0.2
+Copyright (C) 2013, 2015-2017, 2019 Thérèse Godefroy
 You may redistribute this script and/or modify it under the terms
 of the Creative Commons CC0 license.
 EOF
@@ -77,7 +78,7 @@ EOF
 function usage () {
 cat <<EOF
 
-Usage: cvs-sync [OPTIONS] .../www-TEAM
+Usage: ${0##*\/} [OPTIONS] .../www-TEAM
 
   The script assumes the context of www.gnu.org. It synchronizes the
   local reference directory (www) with the CVS repository, and the
@@ -86,17 +87,16 @@ Usage: cvs-sync [OPTIONS] .../www-TEAM
   the local modifications must be made in www-team.
 
 Options:
-  -g GUI_EDITOR         [$geditor]
-      Specify a GUI or PO editor. If none, POs are not displayed.
+  -p PO_EDITOR         [$poeditor]
+      Specify a PO editor. If none, POs are not displayed.
 
-  -n  Do not display the outdated PO in the GUI or PO editor.
+  -n  Do not display the outdated POs in the PO editor.
 
   -a TEAM@ADDRESS       [$address]
       Specify the address of the team mailing list (optional).
       The email will be sent with Mutt.
 
-  -s "SUBJECT_LINE"     [$subject]
-      Specify the path to www-team (required if not in configuration).
+  -s "SUBJECT LINE"     [$subject]
 
   -V  Display version info and exit.
   -h  Display this help and exit.
@@ -110,52 +110,59 @@ Report bugs to <godef.th@free.fr>
 EOF
 }
 
+
 ## Parameters
 
 conf="$HOME/.profile"
 teamdir=""
-geditor=""
+poeditor=""
 display=true
 address=""
-subject="Sync with www $(date +"%y-%m-%d")" # This could be localized.
+subject="Outdated POs $(date +"%y-%m-%d")"
 
 test -s "$conf" && source $conf
 
 # Parse the command line.
 OPTIND=1
-while getopts "h?Va:g:s:n" opt; do
+while getopts "h?Vp:na:s:" opt; do
   case "$opt" in
     h | \? ) usage; exit 0 ;;
     V ) version; exit 0 ;;
-    a ) address=$OPTARG ;;
-    g ) geditor=$OPTARG ;;
-    s ) subject=$OPTARG ;;
+    p ) poeditor=$OPTARG ;;
     n ) display=false ;;
+    a ) address=$OPTARG ;;
+    s ) subject=$OPTARG ;;
   esac
 done
 shift $((OPTIND-1))
 [ "$1" = "--" ] && shift
 
-# Make sure the dependencies are installed (.
-MSGMERGE=$(which msgmerge) \
-|| (echo "!!! msgmerge is not installed."; close_term 1)
-MSGATTRIB=$(which msgattrib) \
-|| (echo "!!! msgattrib is not installed."; close_term 1)
-FUZZY_DIFF=$(which gnun-add-fuzzy-diff) \
-|| echo "*** No diff will be added to the fuzzy strings because
-    gnun-add-fuzzy-diff is not installed."
-MUTT=$(which mutt) \
-|| echo "*** No email will be sent because Mutt is not installed."
+MSGMERGE=$(which msgmerge)
+MSGATTRIB=$(which msgattrib)
+if [ -e "$HOME/bin/gnun-add-fuzzy-diff.1" ]; then
+  FUZZY_DIFF=$HOME/bin/gnun-add-fuzzy-diff.1
+else
+  FUZZY_DIFF=$(which gnun-add-fuzzy-diff) ||
+    echo "*** gnun-add-fuzzy-diff was not found."
+fi
+if [ -n "$poeditor" ] && [ -z "$(which $poeditor)" ]; then
+  echo "*** The specified PO editor is not installed."
+  poeditor=""
+fi
+MUTT=$(which mutt) ||
+  echo "*** No email will be sent because Mutt is not installed."
 
 
 ## Functions
 
 function close_term () {
-  sleep 5
-  exit $1
+  echo -e '\n*** Close the terminal window or press Return.'; read OK
+  test -z "$OK" && exit $1
 }
 
 function check_fuzz () {
+  # Unfuzz if add-fuzzy-diff didn't detect any change.
+  sed -i '/^# || No change/,/^msgid/ { /^msgid/p;d }' "$1"
   # Check for non-deprecated fuzzy strings.
   fuzzy=$(grep -A1 '^#, fuzzy' "$1" |
           sed '/fuzzy/ {N; s,\n,,'} |
@@ -163,8 +170,8 @@ function check_fuzz () {
           grep -c '^#, fuzzy')
 
   # Check for untranslated strings.
-  untr=$(sed -n '/^msgstr ""[[:space:]]*$/ {N;/\n[[:space:]]*$/p}' "$1" \
-       | grep -c msgstr) || true
+  untr=$(sed -n '/^msgstr ""[[:space:]]*$/ {N;/\n[[:space:]]*$/p}' "$1" |
+       grep -c msgstr) || true
   if test "$fuzzy" != "0" -o "$untr" != "0"; then
     return 3
   else
@@ -191,16 +198,16 @@ teamdir="$(pwd)"
 
 ## Update www.
 
-# Make sure www can be reached,
-cd ../www 2>/dev/null \
-|| (echo 1>&2 "!!! $wwwdir doesn't exist or is not reachable.";
-    close_term 1)
-# and is a CVS work tree.
-test -d CVS \
-|| (echo 1>&2 "!!! $wwwdir is not a CVS directory."; close_term 1)
+# Make sure www can be reached,...
+cd ../www 2>/dev/null ||
+  (echo 1>&2 "!!! The www directory doesn't exist or is not reachable.";
+  close_term 1)
+# ... and is a CVS directory.
+test -d CVS ||
+  (echo 1>&2 "!!! $wwwdir is not a CVS directory."; close_term 1)
 wwwdir="$(pwd)"
 
-cvs update
+cvs update || close_term 1
 
 
 ## Synchronize www-team with www, and report.
@@ -215,6 +222,7 @@ if test -d ".git"; then
     echo -e "\n!!! Please move to branch master."
     close_term 1
   fi
+  git pull || true
 fi
 
 # Create temporary files.
@@ -236,23 +244,25 @@ lang=${lang##*.}
 
 # List the POs in www.
 find "$wwwdir" -type f -name "*.$lang.po" |
-        sed "s|$wwwdir|.|;s|po/||;/server\/gnun\//d" | sort > $po_www_list
+  sed "s|$wwwdir|.|;s|po/||;/server\/gnun\//d" | sort > $po_www_list
 
 # Delete the output of the previous run.
-rm -f ../update-report ../update-list ../trivial-list
+rm -f ../update-report ../update-list ../modified-list
 
 # Build the report.
 echo
+
 while read po_team; do
+
   diff_test=0
   fuzz_test_www=0
   fuzz_test_team=0
 
-  section=${po_team%/*}; section=${section#.\/}
+  section=${po_team%/*}; section=${section#./}
   basename=${po_team##*/}
 
   # Test for the presence of the corresponding PO in www, then eliminate
-  # trivial differences and diff the 2 versions of the PO.
+  # some trivial differences and diff the 2 versions of the PO.
   if test -s "../www/$section/po/$basename"; then
     sed 's,charset=utf-8,charset=UTF-8,' \
       "$wwwdir/$section/po/$basename" > "$po_www"
@@ -262,9 +272,15 @@ while read po_team; do
     case $diff_test in
       # There is a difference: merge non-obsolete strings and add the wdiff
       # between old and new msgids.
-      1 ) $MSGATTRIB --no-obsolete "$wwwdir/$section/po/$basename" > "$po_www"
-          $MSGMERGE -U -q --previous "$po_team" "$po_www"
-          test -n $FUZZY_DIFF && $FUZZY_DIFF -i "$po_team"
+      1 ) $MSGATTRIB --no-obsolete "$wwwdir/$section/po/$basename" > "$po_www" ||
+              (2>&1 && close_term $?)
+          $MSGMERGE -U -q --previous "$po_team" "$po_www" || (2>&1 && close_term $?)
+          if [ -n "$FUZZY_DIFF" ]; then
+            $FUZZY_DIFF -i "$po_team"
+            sed -i '/^# || No change/,/^msgid/ { /^msgid/p;d }' "$po_team"
+          else
+            echo "No fuzzy diff."
+          fi
     ;;
       # There is no difference: do nothing.
       0 )
@@ -278,19 +294,18 @@ while read po_team; do
     check_fuzz "$po_team" || fuzz_test_team=$?
 
     case $fuzz_test_team in
+      # Fuzz in www-team
       3 ) case $fuzz_test_www in
             # Fuzz in www: the PO needs updating.
             3 ) echo "$po_team : $fuzzy fuzzy and $untr untranslated."
-               # This could be localized.
                if [ "$po_team1" != "$po_www" ]; then
                  echo "$po_team : $fuzzy fuzzy and $untr untranslated messages." \
                    >> ../update-report
-               fi
-            ;;
+               fi ;;
             # No fuzz in www: most likely the updated version was
             # committed directly to www.
             4 ) cp -b $wwwdir/$section/po/$basename $po_team
-                echo $section/$basename >> ../trivial-list ;;
+                echo $section/$basename >> ../modified-list ;;
             * ) echo "$po_team : !!! Error in the www fuzz test." ;;
           esac
     ;;
@@ -300,11 +315,14 @@ while read po_team; do
             3 ) echo "$po_team seems ready to post." ;;
             # No fuzz in www:
             4 ) if [ "$diff_test" != "0" ]; then
-                  # Same PO-Revision-Date: assume no significant difference.
-                  # Most likely the PO was reformatted by GNUN.
-                  if [ "$(grep 'PO-Revision-Date' $po_team)" = "$(grep 'PO-Revision-Date' $po_www)" ]; then
+                  # Same PO-Revision-Date: most likely the PO was reformatted
+                  # by GNUN. Copy the www version to www-team, but save the old
+                  # file in case the PO had been modified without updating
+                  # PO-Revision-Date.
+                  if [ "$(grep 'PO-Revision-Date' $po_team)" = \
+                       "$(grep 'PO-Revision-Date' $po_www)" ]; then
                     cp -b $wwwdir/$section/po/$basename $po_team
-                    echo $section/$basename >> ../trivial-list
+                    echo $section/$basename >> ../modified-list
                   else
                     echo "$po_team : versions in www and www-team differ."
                   fi
@@ -324,9 +342,10 @@ while read po_team; do
 
 ## Add missing POs to www-team.
 
-  # If the PO is also listed in $po_www_list, remove it from that file.
+  # If the PO is also listed in $po_www_list, remove it from that list.
   grep -v "$po" $po_www_list > $po_www_list1 || true
   mv $po_www_list1 $po_www_list
+
 done < $po_team_list
 
 # If any POs are left in $po_www_list, add them to www-team.
@@ -351,12 +370,10 @@ fi
 if [ -f ../update-report ]; then
   sed -e 's,^\./,,' -e 's, .*,,' ../update-report > ../update-list
 
-  # Display the POs if a GUI/PO editor is set, unless the -n switch is used.
+  # Display the POs if a PO editor is set, unless the -n switch is used.
   if [ "$display" = true ]; then
-    if [ -n "$geditor" ] && [ -n $(which "$geditor") ]; then
-      $geditor $(< ../update-list) &
-    else
-      echo -e "\n*** No valid GUI editor has been specified."
+    if [ -n "$poeditor" ]; then
+      $poeditor $(< ../update-list) &
     fi
   fi
 
@@ -375,17 +392,14 @@ if [ -f ../update-report ]; then
     fi
   fi
 else
-  echo "*** No new outdated PO."
+  echo -e "\n*** No new outdated PO."
 fi
 
-
-## Commit up-to-date POs to www-team.
-
-if [ -d .git ] && [ -f ../trivial-list ]; then
-  git add $(< ../trivial-list)
-  git commit -m "Sync with www." || true
+if [ -f ../modified-list ]; then
+  echo -e "\n*** Modified files with same PO-Revision-Date, copied to www-team:"
+  cat ../modified-list
 fi
 
-echo -e "\n*** Done.\n"
+echo -e "\n*** Done."
 
 close_term 0
diff --git a/micro-www-checkout b/micro-www-checkout
--- a/micro-www-checkout
+++ b/micro-www-checkout
@@ -1,62 +1,64 @@
 #!/bin/bash
 
 # NAME
-#    micro-www-checkout - create a minimized www directory for transvalid-batch
+#    micro-www-checkout - check out a subset of www for transvalid-batch
 
 # SYNOPSIS
-#    micro-www-checkout -t .../www-TEAM [-l 'LANG1 [LANG2]...'] [-u CVS_LOGIN]
-#    or
-#    micro-www-checkout -l 'LANG1 [LANG2]...' [-u CVS_LOGIN]
+#    micro-www-checkout [-u SAVANNAH_USER] [-c] [-a] [LANG]
+#                       (options first)
 
 # DEPENDENCIES
 #    cvs, rsync
 
 # DESCRIPTION
-#    This script checks out the files required by transvalid-po to generate
-#    HTML pages from POs for a specific language and validate them.
-#    Transvalidation with GNUN requires some additional files.
+#    This script checks out the files required to use cvs-sync,
+#    transvalid-po and transvalid-batch. Synchronization and transvalidation
+#    with GNUN require some additional files. 
 #
 #    Method:
-#    1. A list of the potentially useful files is obtained from a dry run of
+#    1. Directories:
+#       - If both www and www-LANG (also called www-TEAM) exist, they should
+#         have the same parent.
+#       - The script can be called from www-LANG, www or their parent dir.
+#       - If the script is called from www-LANG, any other LANG argument
+#         is dropped. Otherwise, LANG must be given as a command-line
+#         argument or as user input.
+#       - The same www dir can be used for several languages.
+#       - If www-LANG doesn't exist, it is optionally created.
+#    2. A list of the potentially useful files is obtained from a dry run of
 #       rsync on the CVS repository, exluding irrelevant directories and
 #       keeping only files with .po and .html extensions.
-#    2. The rsync list is further processed to build a checkout list
-#       containing the language-specific POs and the corresponding original
-#       HTMLs.
-#    3. The listed files are downloaded by cvs (with login if the ID is
-#       provided, otherwise anonymous).
+#    3. The rsync list is further processed to build a checkout list
+#       containing: 
+#       - POs that reside in www (*.LANG.po);
+#       - unGNUNified translations (*.LANG.html);
+#       - English originals (*.html) that correspond to POs from www and/or
+#         www-LANG.
+#    4. The listed files are checked out by cvs, using a login if provided,
+#       otherwise anonymous. (The Savannah user name can be entered on the
+#       command line or in the "savannah_user" variable around line 84.)
+#       If www already exists, it is simply updated.
+#    5. The POs that are found in www but not in www-LANG are optionally added
+#       to www-LANG.
 #
-#    Disadvantage:
-#    Update of the micro-www directory does not download the original HTMLs
-#    that have not been translated to the selected language. Those must be
-#    checked out separately. The corresponding POT files must be downloaded
-#    once to create the PO but they don't need to be tracked if www and
-#    www-team are updated with cvs-sync (they would be required by the sync
-#    target of GNUN).
-#
-# OPTIONS AND CURRENT SETTINGS
-#    Displayed by:   micro-www-checkout -h
-#
-#    Configuration file ($conf):
-#    The command-line parameters can be set once and for all in a configuration
-#    file (also used by transvalid-batch, www-commit, cvs-sync, and
-#    check-links), with the syntax:
-#       parameter1="value1"
-#       parameter2="value2"
-#    This configuration overrides the default settings but is superseded by the
-#    command line. The file ($conf) is defined under "Parameters".
-#    The files corresponding to the team specified in the profile will always
-#    be checked out, provided www-team exists locally.
+#    To make a new translation, the POT file must be downloaded once to
+#    create the PO, but it doesn't need to be tracked. After the new PO is
+#    added to www-LANG, micro-www-checkout can be run again to add the
+#    English original to www.
+
+# OPTIONS 
+#    Displayed by "micro-www-checkout -h".
+#    The Savannah user name can be defined in a configuration file, as for
+#    cvs-sync and www-commit.
 
 #==============================================================================
 
 set -e
-set -o pipefail
 
 function version () {
 cat <<EOF
-${0##*\/} version 0.1
-Copyright (C) 2013, 2014 Thérèse Godefroy
+${0##*\/} version 0.2
+Copyright (C) 2013, 2016, 2019 Thérèse Godefroy
 You may redistribute this script and/or modify it under the terms
 of the Creative Commons CC0 license.
 EOF
@@ -66,30 +68,22 @@ function usage () {
 cat <<EOF
 
 Usage:
-  micro-www-checkout -t .../www-TEAM [-l 'LANG1 [LANG2]...'] [-u CVS_LOGIN]
-  or  micro-www-checkout -l 'LANG1 [LANG2]...' [-u CVS_LOGIN]
+  ${0##*\/} [-u SAVANNAH_USER] [-c] [-a] [LANG]
+            (options first)
+    
+  This script checks out a subset of the www.gnu.org cvs repo,
+  essentially *.LANG.po and corresponding *.html, for use with
+  cvs-sync, transvalid-po and transvalid-batch.
 
-  The script checks out the POs for a list of languages and the
-  corresponding original pages, from the CVS repo of www.gnu.org.
+  If the www-LANG directory doesn't exist, it is optionally created.
 
 Options and current settings:
-
-  -l 'LANG1 LANG2...'        [$langs]
-      Specify one or several space-separated language codes (one
-      code is required if no working directory is specified).
-
-  -u CVS_LOGIN               [$user]
+  -u SAVANNAH_USER               [$savannah_user]
       Specify your login if you have write access to www (optional).
-
-  -t .../www-TEAM            [$teamdir]
-      Specify the team directory (required if no language code is given).
-
+  -c  Create the team directory (www-LANG) if it doesn't exist.
+  -a  Add missing POs to www-LANG.
   -V  Display version info and exit.
   -h  Display this help and exit.
-
-The parameters can be specified in a configuration file:
-      $conf
-One line per parameter, with syntax: param='VALUE'
 
 Report bugs to <godef.th@free.fr>
 
@@ -101,80 +95,76 @@ function close_term () {
   exit $1
 }
 
-
-echo "${0##*\/} - create a minimized www directory for transvalid-batch"
-
-## Parameters
-
+# Initial parameters:
 conf="$HOME/.profile"
-langs=""
-teamdir=""
-user="anonymous"
-protocole="pserver"
+savannah_user="anonymous"
+create_teamdir=""
+add_missing=""
 test -s "$conf" && source $conf
-
 
 # Parse the command line.
 OPTIND=1
-while getopts "h?Vl:t:u:" opt; do
+while getopts "h?Vu:ca" opt; do
   case "$opt" in
     h | \? ) usage; exit 0 ;;
     V ) version; exit 0 ;;
-    l ) langs=$OPTARG ;;
-    t ) teamdir=$OPTARG ;;
-    u ) user=$OPTARG ;;
+    u ) savannah_user=$OPTARG ;;
+    c ) create_teamdir=1 ;;
+    a ) add_missing=1 ;;
   esac
 done
 shift $((OPTIND-1))
 [ "$1" = "--" ] && shift
 
-
-## Get valid language codes
-
-# Several methods:
-# - from the command line or conf file;
-langs=($langs)
-n=${#langs[@]}
-
-# - from the name of the team directory if it exists (move to its parent dir);
-if test "$teamdir" != "$HOME" -a -d "$teamdir"; then
-  cd "$teamdir" && cd ../
-  l=${teamdir#*www-}
-  langs[$n]=$l
-else                  # (or else create the parent dir of www and move there);
-  mkdir -p $HOME/GNU && cd $HOME/GNU
+# Get the language code...
+if [[ "$PWD" =~ 'www-' ]]; then  # ... from the name of the team dir,
+  l=${PWD#*www-}
+elif [ -n "$1" ]; then           # ... or from the command line,
+  l=$1
+else                             # ... or from user input.
+  echo "Please enter a language code."
+  read l
 fi
 
-# - from user input.
-if test -z "$langs"; then
-  echo -e "\n*** Please enter one or several language codes."; read l
-  langs=($l)
-fi
-
-# Test the validity of the language codes.
+# Test the validity of the language code.
 ref_lang_codes='af ar az bg bn bs ca cs da de el en eo es et fa fi fr gl he \
 hr hu id it ja kn ko mk ml lt nb nl nn pl pt pt-br ro ru sh sk sl sq sr sv ta \
-th tl tr uk uz vi zh-cn zh-tw'
-(vlangs)=""
-for l in ${langs[@]}; do
-  [[ "$ref_lang_codes" =~ "$l" ]] && vlangs=($vlangs $l)
-done
-test -z "$vlangs" && (echo 1>&2 "!!! No valid language."; close_term 1)
+te th tl tr uk uz vi zh-cn zh-tw'
 
+[[ "$ref_lang_codes" =~ "$l" ]] ||
+  (echo 1>&2 "!!! Not a valid language code."; close_term 1)
+lang=$l
 
-## List the relevant files in www
+echo "language code: $lang"
 
-# Create temporary files.
-TMP1=$(mktemp -t co.XXXXXX) || close_term 1  # rsync output
-TMP2=$(mktemp -t co.XXXXXX) || close_term 1  # *.lang.po
-TMP3=$(mktemp -t co.XXXXXX) || close_term 1  # *.lang.html / co list: verified
-TMP4=$(mktemp -t co.XXXXXX) || close_term 1  # checkout list: rough / final
-trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4"' EXIT
-
-if [ -d "www" ]; then
-  mv www www.bak || close_term 1
+if [[ "$PWD" =~ www ]]; then
+  cd ../
 fi
 
+# Optionally create www-LANG if it doesn't exist.
+if [ ! -d www-$lang ] && [ "$create_teamdir" == '1' ]; then
+  echo "Creating the www-$lang directory."
+  mkdir www-$lang || (echo 1>&2 "Can't make www-$lang."; close_term 1) 
+fi
+
+
+## Select files to check out.
+
+# Create temporary files.
+TMP1=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP1"; exit 1)
+TMP2=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP2"; exit 1)
+TMP3=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP3"; exit 1)
+TMP4=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP4"; exit 1)
+TMP5=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP5"; exit 1)
+trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4" "$TMP4"' EXIT
+
+# List the POs in www-LANG.
+if [ -d "www-$lang" ]; then
+  find www-$lang -name '*.po' > $TMP2
+fi
+
+echo "${0##*\/} - create a minimized www directory for $lang
+"
 # List the files in the www repository with a dry run of rsync, excluding
 # some irrelevant directories and files. The destination directory is
 # specified to avoid listing the file attributes, but it is not created.
@@ -198,44 +188,67 @@ sed -i -e '/^www/!d' \
        -e '/\/$/d' \
        -e 's:,v$::' $TMP1
 
-# Select what's needed for each language.
-# NOTE: if some translations are not gnunified, lines (1), (2), (3)  and (5)
-# should be uncommented, and line (4) may be commented out.
+# Select POs in www that have counterparts in www-LANG.
+sed -i "s:^www-$lang:www:" $TMP2               # *LANG.po in www-LANG
+sed "s:\([^/]*$lang\\.po\)$:po/\1:" $TMP2 > $TMP3 
 
-for lang in ${vlangs[@]}; do
-  echo "language code: $lang"
+# Select POs in www (some of them may not be in www-LANG).
+grep "[./]$lang\.po$" $TMP1 > $TMP2 || true    # *LANG.po in www
 
-  sed -n "/\\.$lang\\.po/p" $TMP1 > $TMP2                         # *.lang.po
-  cat $TMP2 >> $TMP4
-#  sed -n "/\\.$lang\\.html/p" $TMP1 > $TMP3                       # (1) *.lang.html
-#  cat $TMP3 >> $TMP4                                              # (2)
-#  sed "s:\\.po$:-diff.html:" $TMP3 >> $TMP4                       # (3) *.lang-diff.html
-  sed "s:po/\\([^/]*\\)\\.$lang\\.po$:\\1.html:" $TMP2  >> $TMP4  # (4) from *.lang.po
-#  sed "s:$lang\\.html$:html:" $TMP3 >> $TMP4                      # (5) from *.lang.html
+# Figure out which POs are in www but not www-LANG.
+while read f; do
+  grep -q "$f" $TMP3 || echo "$f" >> $TMP4
+done < $TMP2  # POS in www
 
-  # Check that all the listed files exist (some POs may not have corresponding
-  # HTMLs because they have been renamed or misplaced, or the HTML has been
-  # removed from the repository).
-  while read f; do
-    grep "$f" $TMP1 >> $TMP3 || true
-  done < $TMP4
-done
+# Add the corresponding originals to the checkout list.
+sed "s:po/\([^/]*\)\\.$lang\\.po$:\1.html:" $TMP2 > $TMP3
+cat $TMP3 >> $TMP2                              # ==> *.html
 
-# List each file only once
-sort $TMP3 | uniq > $TMP4
+#### If some translations are not GNUNified, uncomment (1) to (3). #####
+
+# Select all HTML translations...
+#grep ".$lang.html$" $TMP1 > $TMP3 || true      # (1)
+#cat $TMP3 >> $TMP2                             # (2) *.LANG.html
+# ... and the corresponding originals.
+#sed "s:$lang\.html$:html:" $TMP3 >> $TMP2      # (3) ==> *.html
+
+# Sort alphabetically and remove duplicates.
+sort $TMP2 | uniq > $TMP3
+
+# Make sure all the selected files exist (some POs may not correspond to any
+# originals because they have been renamed or misplaced, or the originals
+# have been removed from the repository).
+while read f; do
+  grep "$f" $TMP1 >> $TMP5 || true
+done < $TMP3
 
 
-## Checkout the listed files.
+## Check out the selected files.
 
-if [ -s $TMP4 ]; then
+if [ -s "$TMP5" ]; then
   # Define the protocole.
-  if test -n "$user" -a "$user" != "anonymous"; then
+  if test -n "$savannah_user" -a "$savannah_user" != "anonymous"; then
     protocole="ext"
+  else
+    protocole="pserver"
   fi
-  cvs -z3 -d:$protocole:$user@cvs.savannah.gnu.org:/webcvs/www co $(< $TMP4)
-
+  echo "*** Creating or updating the www directory.
+"
+  cvs -z3 -d:$protocole:$savannah_user@cvs.sv.gnu.org:/web/www co $(< $TMP5)
 else
-  echo  1>&2 "!!! There is no file in the checkout list." && close_term 1
+  echo  1>&2 "!!! There is no file in the checkout list."; close_term 1
+fi
+
+if [ "$add_missing" == "1" ] && [ -s "$TMP4" ]; then
+  cd www-$lang
+  echo "*** Adding missing POs to www-$lang."
+
+  while read f; do
+    f1=${f/\/po\//\/} && f1=${f1/www\//}
+    dir=$(dirname "$f1")
+    mkdir -p $dir
+    cp ../"$f" "$f1"
+  done < $TMP4
 fi
 
 exit 0
diff --git a/www-commit b/www-commit
--- a/www-commit
+++ b/www-commit
@@ -4,7 +4,7 @@
 #    www-commit - batch commit to the www repository
 
 # SYNOPSIS
-#    www-commit  -t /.../www-TEAM
+#    www-commit .../www-TEAM
 
 # DEPENDENCIES
 #    required: cvs, git.
@@ -19,15 +19,15 @@
 #    * www and www-team must have the same parent directory.
 #    * www-team must be a Git repository and contain the working copies of the
 #      PO files.
-#    * www must contain the PO files under CVS control
+#    * www must contain the PO files under CVS control.
 
 # OPTIONS AND CURRENT SETTINGS
-#    Displayed by:   cvs-sync -h
+#    Displayed by:   www-commit -h
 #
 #    Configuration file:
 #    The command-line parameters can be set once and for all in a configuration
-#    file (also used by transvalid-batch, cvs-sync, www-commit, and
-#    micro-www-checkout), with the syntax:
+#    file (also used by transvalid-batch, cvs-sync, micro-www-checkout and
+#    check-links, with the syntax:
 #       parameter1="value1"
 #       parameter2="value2"
 #    This configuration overrides the default settings but is superseded by the
@@ -40,8 +40,8 @@ set -o pipefail
 
 function version () {
 cat <<EOF
-${0##*\/} version 0.1
-Copyright (C) 2013, 2014 Thérèse Godefroy
+${0##*\/} version 0.2
+Copyright (C) 2015, 2016, 2019 Thérèse Godefroy
 You may redistribute this script and/or modify it under the terms
 of the Creative Commons CC0 license.
 EOF
@@ -50,7 +50,7 @@ EOF
 function usage () {
 cat <<EOF
 
-Usage: cvs-sync  -t /.../www-TEAM
+Usage: ${0##*\/} .../www-TEAM
 
   The script assumes the context of www.gnu.org, with the team directory
   (www-team) under Git. It copies the modified POs from www-team to www,
@@ -58,9 +58,6 @@ Usage: cvs-sync  -t /.../www-TEAM
   www CVS repository. www and www-team must have the same parent directory.
 
 Options:
-
-  -t /.../www-TEAM         [$teamdir]
-      Specify the absolute path to www-team (required)
   -V  Display version info and exit.
   -h  Display this help and exit.
 
@@ -70,35 +67,9 @@ EOF
 }
 
 function close_term () {
-  sleep 10
-  exit $1
+  echo -e '\n*** Close the terminal window or press Return.'; read OK
+  test -z "$OK" && exit $1
 }
-
-echo "${0##*\/} - batch commit to the www repository"
-
-
-## Parameters
-
-conf="$HOME/.profile"
-teamdir=""
-test -s "$conf" && source $conf
-
-# Parse the command line.
-OPTIND=1
-while getopts "h?Vt:" opt; do
-  case "$opt" in
-    h | \? ) usage; exit 0 ;;
-    V ) version; exit 0 ;;
-    t ) teamdir=$OPTARG ;;
-  esac
-done
-shift $((OPTIND-1))
-[ "$1" = "--" ] && shift
-
-
-conf="$HOME/.profile"
-test -f $conf && source $conf
-
 
 function select_message () {
 # lets the user select a message from the configuration file.
@@ -112,7 +83,7 @@ function select_message () {
         [other] no commit"
   read -s -n1 choice
   case "$choice" in
-    0) echo "Quel est le message de commit ?"; read message ;;
+    0) echo "What is the message?"; read message ;;
     1) message=$message11 ;;
     2) message=$message12 ;;
     3) message=$message13 ;;
@@ -122,9 +93,39 @@ function select_message () {
   esac
 }
 
-cd $teamdir
+echo "${0##*\/} - batch commit to the www repository"
 
-# Create TMP files
+# Initial parameters
+conf="$HOME/.profile"
+teamdir=""
+copyonly=""
+test -s "$conf" && source $conf
+
+# Parse the command line.
+OPTIND=1
+while getopts "h?V" opt; do
+  case "$opt" in
+    h | \? ) usage; exit 0 ;;
+    V ) version; exit 0 ;;
+  esac
+done
+shift $((OPTIND-1))
+[ "$1" = "--" ] && shift
+
+# Team directory input
+test -n "$1" && teamdir=$1
+if test ! -d "$teamdir"; then
+  echo -e "\n*** Please specify your team directory."; read teamdir
+fi
+teamdir=${teamdir%\'}; teamdir=${teamdir#\'}
+# Make sure it can be reached.
+cd "$teamdir" \
+|| (echo 1>&2 "!!! Can't reach $teamdir."; close_term 1)
+
+lang=${teamdir##*www-}
+
+
+# Create TMP files.
 batch1=$(mktemp -t commit.XXXXXX) || exit 1
 batch2=$(mktemp -t commit.XXXXXX) || exit 1
 batch3=$(mktemp -t commit.XXXXXX) || exit 1
@@ -132,39 +133,61 @@ batch4=$(mktemp -t commit.XXXXXX) || exit 1
 d=$(mktemp -t commit.XXXXXX) || exit 1
 trap 'rm -f "$batch1" "$batch2" "$batch3" "$batch4" "$d"' EXIT
 
-# Get lists of modified POs
+# Get lists of modified POs.
 git dn master master^ > $batch1
 git dn master^ master^^ > $batch2
 git dn master^^ master^^^ > $batch3
-git dn master^^^ master^^^^ > $batch4
 
+# Copy and commit.
 echo ''
-for s in $batch1 $batch2 $batch3 $batch4; do
-  echo -e "\n=== Batch to be committed:\n"
-  cat $s                                      # source list (in www-team)
-  sed -e 's,\([^/]*.fr.po\),po/\1,' $s > $d   # destination list (in www)
-  sfiles=($(< $s))                            # source array
-  dfiles=($(< $d))                            # destination array
+n=0
+for s in $batch1 $batch2 $batch3; do
+  let n=n+1 
+  echo -e "\n=== Batch #$n:\n"
+  cat $s                                            # source list (in www-team)
 
-  select_message
-  if [ -z "$message" ]; then
+  echo "        [0] skip
+        [1] copy only
+        [2] commit
+        [other] quit"
+  read -s -n1 choice
+  case "$choice" in
+    0 ) continue ;;
+    1 ) copyonly=1 ;;
+    2 ) copyonly="" ;;
+    * ) exit 0 ;;
+  esac
+
+  sed -e "s,\\([^/]*$lang\\.po\\),po/\\1," $s > $d  # destination list (in www)
+  sfiles=($(< $s))                                  # source array
+  dfiles=($(< $d))                                  # destination array
+
+  i=0
+  while [ "$i" -lt ${#sfiles[@]} ]; do
+    cp ${sfiles[$i]} ../www/${dfiles[$i]}   # copy file from www-team to www
+    cp ${sfiles[$i]} /media/Gnu-local/www/${dfiles[$i]}
+    let i=i+1
+  done
+  if [ -z "$copyonly" ]; then
+    select_message
+    if [ -z "$message" ]; then
       echo "This batch will not be committed."
-  else
-    i=0
-    while [ "$i" -lt ${#sfiles[@]} ]; do
-      cp ${sfiles[$i]} ../www/${dfiles[$i]}   # copy file from www-team to www
-      let i=i+1
-    done
-    echo "cvs commit -m \"$message\" $(< $d)"
-    echo "OK this commit."
-    read -s -n1 OK
-    if [ -z "$OK" ]; then
-      cd ../www && cvs commit -m "$message" $(< $d)
-      echo "Done."
-      cd ../www-fr
     else
-      echo "Not committed."
+      echo "cvs commit -m \"$message\" $(< $d)"
+      echo "OK this commit."
+      read -s -n1 OK
+      if [ -z "$OK" ]; then
+        cd ../www && cvs commit -m "$message" $(< $d) ||
+          (echo 1>&2 "!!! Unable to commit"; close_term 1)
+        echo "Done."
+        cd $teamdir
+      else
+        echo "Copied to www; not committed."
+      fi
     fi
+  else
+    echo "Copied to www; not committed."
   fi
 done
-exit
+
+exit 0
